const UA = 'klgzapp-batch-dl/1.0';

export function normalizeUrl(raw) {
  let text = String(raw || '').trim();
  if (!text || text.startsWith('#')) return '';
  const idx = text.lastIndexOf('https://');
  if (idx > 0) text = text.slice(idx);
  if (!/^https?:\/\//i.test(text)) {
    if (text.startsWith('/')) text = `https://cdn.novagirl.app${text}`;
    else return '';
  }
  try {
    return new URL(text).href;
  } catch {
    return '';
  }
}

export function parseUrlList(text) {
  const seen = new Set();
  const urls = [];
  for (const line of String(text || '').split(/\r?\n/)) {
    const url = normalizeUrl(line);
    if (!url || seen.has(url)) continue;
    seen.add(url);
    urls.push(url);
  }
  return urls;
}

export function sliceRange(urls, fromRaw, toRaw) {
  const total = urls.length;
  let from = Number(fromRaw);
  let to = Number(toRaw);
  if (!Number.isFinite(from) || from < 1) from = 1;
  if (!Number.isFinite(to) || to < 1) to = total;
  from = Math.min(Math.max(1, Math.floor(from)), total || 1);
  to = Math.min(Math.max(from, Math.floor(to)), total || 1);
  return { from, to, items: urls.slice(from - 1, to) };
}

export function destName(url, index, numbered) {
  let name = 'file.bin';
  try {
    const path = new URL(url).pathname;
    name = decodeURIComponent(path.split('/').pop() || name);
  } catch {
    /* keep default */
  }
  name = name.replace(/[\\/:*?"<>|]+/g, '_') || 'file.bin';
  if (numbered) name = `${String(index).padStart(3, '0')}_${name}`;
  return name;
}

export function buildPythonScript(urls, outDir) {
  const folder = (outDir || 'downloads').replace(/['\\]/g, '');
  const listed = urls.map((u) => JSON.stringify(u)).join(',\n    ');
  return `#!/usr/bin/env python3
"""klgzapp batch downloader — generated by www.klgzapp.com/?tool=batch-dl"""

from __future__ import annotations

import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

OUT = Path(${JSON.stringify(folder)})
URLS = [
    ${listed}
]
UA = ${JSON.stringify(UA)}
WORKERS = 8
TIMEOUT = 180
RETRIES = 3


def dest_for(url: str) -> Path:
    name = Path(url.split("?", 1)[0]).name or "file.bin"
    return OUT / name


def download_one(url: str, dest: Path) -> tuple[str, str]:
    if dest.exists() and dest.stat().st_size > 0:
        return ("exists", dest.name)
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    last_err = ""
    for attempt in range(1, RETRIES + 1):
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        try:
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp, open(tmp, "wb") as f:
                while True:
                    chunk = resp.read(1024 * 256)
                    if not chunk:
                        break
                    f.write(chunk)
            if tmp.stat().st_size <= 0:
                raise OSError("empty file")
            tmp.replace(dest)
            return ("ok", dest.name)
        except Exception as exc:
            last_err = str(exc)
            if tmp.exists():
                tmp.unlink(missing_ok=True)
            if attempt < RETRIES:
                time.sleep(attempt)
    return ("err", f"{dest.name} <- {url} :: {last_err}")


def main() -> None:
    jobs = [(url, dest_for(url)) for url in URLS]
    OUT.mkdir(parents=True, exist_ok=True)
    print(f"queued: {len(jobs)} -> {OUT.resolve()}", flush=True)
    stats = {"ok": 0, "exists": 0, "err": 0}
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futs = [ex.submit(download_one, url, dest) for url, dest in jobs]
        for i, fut in enumerate(as_completed(futs), 1):
            status, detail = fut.result()
            stats[status] = stats.get(status, 0) + 1
            if status == "err":
                print(f"ERR {detail}", flush=True)
            if i % 20 == 0 or i == len(futs):
                print(f"progress {i}/{len(futs)} {stats}", flush=True)
    print("DONE", stats, flush=True)
    if stats["err"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
`;
}

async function writeFile(dirHandle, name, blob) {
  const handle = await dirHandle.getFileHandle(name, { create: true });
  const writable = await handle.createWritable();
  await writable.write(blob);
  await writable.close();
}

async function fetchBlob(url) {
  const resp = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.blob();
}

export async function downloadToDirectory(items, dirHandle, { workers = 4, numbered = false, onItem } = {}) {
  const stats = { ok: 0, exists: 0, err: 0 };
  let cursor = 0;

  async function worker() {
    while (cursor < items.length) {
      const i = cursor;
      cursor += 1;
      const url = items[i];
      const name = destName(url, i + 1, numbered);
      try {
        const existing = await dirHandle.getFileHandle(name).catch(() => null);
        if (existing) {
          const file = await existing.getFile();
          if (file.size > 0) {
            stats.exists += 1;
            onItem?.({ index: i + 1, name, url, status: 'exists' });
            continue;
          }
        }
        const blob = await fetchBlob(url);
        if (!blob.size) throw new Error('empty file');
        await writeFile(dirHandle, name, blob);
        stats.ok += 1;
        onItem?.({ index: i + 1, name, url, status: 'ok', size: blob.size });
      } catch (err) {
        stats.err += 1;
        onItem?.({
          index: i + 1,
          name,
          url,
          status: 'err',
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  const n = Math.max(1, Math.min(Number(workers) || 4, 8));
  await Promise.all(Array.from({ length: Math.min(n, items.length) }, () => worker()));
  return stats;
}
